app:
  client-list-page:
    msg: Привет мир!!!

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: postgres
    password: postgre
  flyway:
    enabled: true
    clean-on-validation-error: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE